baseURL: 'https://arizerner.com'
languageCode: 'en-us'
title: Ari Zerner's Demesne
theme: ["hugo-embed-pdf-shortcode", "PaperMod"]

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Contact
      url: /contact/
      weight: 10
    - identifier: "resume"
      name: "Resumé"
      url: "/resume/"
      weight: 15
    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: 20
    - identifier: "recipes"
      name: "Recipes"
      url: "/recipes/"
      weight: 30
    - identifier: "recommendations"
      name: "Recommendations"
      url: "/recommendations/"
      weight: 40
    - identifier: "private-chef"
      name: "Private Chef Website"
      url: "https://aricooks.com"
      weight: 47
    - identifier: "canary"
      name: "Canary"
      url: "/canary/"
      weight: 50
    - identifier: "old-travel-blog"
      name: "Old Travel Blog"
      url: "https://arizerner.travel.blog"
      weight: 100

params:
  title: Ari Zerner's Demesne
  mainSections: ["posts"]
  ShowBreadCrumbs: true
  ShowLastMod: true
  math: false

taxonomies:
  tag: "tags"
  
permalinks:
  posts: "/posts/:slug/"
  recipes: "/recipes/:slug/"

enableGitInfo: true

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          inline:
          - - $$
            - $$
        enable: true

