baseURL: 'http://arizerner.com'
languageCode: 'en-us'
title: Ari Zerner's Demesne
theme: PaperMod

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Contact
      url: /contact/
      weight: 10
    - identifier: "resume"
      name: "Resumé"
      url: "/resume/"
      weight: 20
    - identifier: "recipes"
      name: "Recipes"
      url: "/recipes/"
      weight: 30
    - identifier: "recommendations"
      name: "Recommendations"
      url: "/recommendations/"
      weight: 40
    - identifier: "canary"
      name: "Canary"
      url: "/canary/"
      weight: 50

params:
  title: Ari Zerner's Demesne
  mainSections: ["posts"]
  ShowBreadCrumbs: true

taxonomies:
  tag: "tags"
  
permalinks:
  posts: "/posts/:slug/"
  recipes: "/recipes/:slug/"
