baseURL: 'http://arizerner.com'
languageCode: 'en-us'
title: Ari Zerner's Demesne
theme: PaperMod

menu:
  main:
    - name: About/Contact
      url: /about/
      weight: 10
    - identifier: "resume"
      name: "Resumé"
      url: "/resume/"
      weight: 20
    - identifier: "recipes"
      name: "Recipes"
      url: "/recipes/"
      weight: 30

params:
  title: Ari Zerner's Demesne
  author: Ari Zerner
  mainSections: ["posts"]
  ShowBreadCrumbs: true

taxonomies:
  tag: "tags"
  
permalinks:
  posts: "/posts/:slug/"
  recipes: "/recipes/:slug/"
